language: ruby
rvm:
  - 2.1
branches:
  only:
    publish
before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site

after_script:
  - postsuccess.sh

notifications:
  email: false
