title:            Sandeep Chivukula
description:      Technology Business
disqus_shortname:
logo:             site-logo.png
disqus_shortname:
search:           true
#Comment out url when working locally to resolve base urls correctly
url:              http://sandeep.github.io
#For Development Only
#url:             http://localhost:3000

# Owner/author information
owner:
  name:           Sandeep Chivukula
  avatar:         Profile_Pic.jpg
  email:          me@sandeepchivukula.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        _sandeep
  #facebook:
  github:         sandeep
  stackexchange:
  linkedin:       sandeepchivukula
  #instagram:
  #flickr:
  #itumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-22827765-1
google_verify: RCIETChG8zO8BGrHTNgEZYZWfKj-J2jdUthBRvD7DRA
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
 # - title: About
 #   url: /index.html
  - title: Posts
    url: /posts
#  - title: Photos
#    url: /Photos
#  - title: Made Mistakes
#    url: http://mademistakes.com
#    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
